---
- hosts: windows_servers  # Replace with your windows server group

  roles:
    - nginx  # Replace with the actual role path containing the tasks

  vars:
    nginx_version: "latest"  # Adjust if needed

  tasks:
    - name: Install Chocolatey (pre-requisite for package management)
      win_get:
        url: https://chocolatey.org/install.ps1
        dest: C:\Users\Admin\Downloads\chocolatey.ps1
        state: present
      become: true

    - name: Install Chocolatey (needs admin rights)
      win_command: PowerShell -ExecutionPolicy Bypass -NoProfile -File C:\Users\Admin\Downloads\chocolatey.ps1
      become: true

    - name: Install Nginx using Chocolatey
      win_chocolatey:
        name: nginx
        version: "{{ nginx_version }}"
        state: present

    - name: Install NSSM for service management
      win_chocolatey:
        name: nssm
        state: present

    - name: Copy Nginx configuration (replace with your actual config file)
      win_copy:
        src: path/to/your/nginx.conf
        dest: C:\nginx\conf\nginx.conf
        remote_owner: Administrator

    - name: Create Nginx service using NSSM
      win_nssm:
        service_name: nginx
        program_path: C:\nginx\nginx.exe
        arguments: "-c C:\nginx\conf\nginx.conf"
        state: present
        start: yes  # Set to no if you want to start manually

      handlers:
        - name: Restart Nginx service after creating it
          win_service:
            name: nginx
            state: restarted
          become: true
        when: service_changed
