---
- name: Ensure Nginx is running on Windows
  hosts: windows
  tasks:
    - name: Check if nginx.exe exists
      win_shell: Test-Path -Path 'C:\\Users\\Admin\\Downloads\\nginx\\nginx-1.18.0\\nginx.exe'
      register: path_exists

    - name: Print path check result
      debug:
        var: path_exists

    - name: Start Nginx if executable exists
      win_shell: Start-Process -FilePath 'C:\\Users\\Admin\\Downloads\\nginx\\nginx-1.18.0\\nginx.exe' -NoNewWindow -Wait
      when: path_exists.stdout == "True"
