---
- name: Download, Extract, and Install NGINX on Windows
  hosts: 172.16.0.67
  tasks:
    - name: Ensure download directory exists
      ansible.windows.win_file:
        path: C:\Users\Admin\Downloads
        state: directory

    - name: Download NGINX zip file
      ansible.windows.win_get_url:
        url: https://nginx.org/download/nginx-1.18.0.zip
        dest: C:\Users\Admin\Downloads\nginx.zip

    - name: Extract NGINX zip file
      ansible.windows.win_shell: |
        Expand-Archive -Path C:\Users\Admin\Downloads\nginx.zip -DestinationPath C:\Users\Admin\Downloads\nginx

    - name: Install NGINX
      ansible.windows.win_command: C:\Users\Admin\Downloads\nginx\nginx-1.18.0\nginx.exe /S
