- name: Install nginx
  ansible.windows.win_command: |
    C:\Users\Admin\Downloads\nginx\nginx-1.18.0\nginx.exe /S
  args:
    chdir: C:\Users\Admin\Downloads\nginx\nginx-1.18.0
  register: nginx_install_result

- name: Debug - NGINX installation result
  ansible.builtin.debug:
    var: nginx_install_result
