- name: Install and configure nginx on Windows
  hosts: 172.16.0.67
  tasks:
    - name: Ensure the download directory exists
      ansible.windows.win_file:
        path: C:\User\Admin\Downloads
        state: directory

    - name: Download nginx
      ansible.windows.win_get_url:
        url: https://nginx.org/download/nginx-1.18.0.zip
        dest: C:\User\Admin\Downloads\nginx.zip

    - name: Ensure the nginx directory exists
      ansible.windows.win_file:
        path: C:\nginx
        state: directory

    - name: Ensure nginx is not running
      ansible.windows.win_shell: |
        Stop-Process -Name nginx -Force -ErrorAction SilentlyContinue
      ignore_errors: yes

    - name: Unzip nginx
      community.windows.win_unzip:
        src: C:\User\Admin\Downloads\nginx.zip
        dest: C:\nginx
        creates: C:\nginx\nginx.exe

    - name: Ensure nginx is not installed
      ansible.windows.win_package:
        name: nginx
        state: absent

    - name: Start nginx
      ansible.windows.win_command: |
        Start-Process -NoNewWindow -FilePath "C:\nginx\nginx.exe"
